<x-section-card>
<p class="mb-4 font-semibold">{{ $order->event->title }}</p>
<dl class="space-y-3"><div><dt class="text-sm text-slate-600">Referensi</dt><dd class="break-all font-semibold">{{ $order->order_ref }}</dd></div><div><dt class="text-sm text-slate-600">Paket</dt><dd>{{ $order->package_snapshot['name'] }}</dd></div><div><dt class="text-sm text-slate-600">Nominal</dt><dd>Rp {{ number_format($order->amount,0,',','.') }} ({{ $order->currency }})</dd></div><div><dt class="text-sm text-slate-600">Status server</dt><dd>{{ $order->status }}</dd></div><div><dt class="text-sm text-slate-600">Pembayaran terverifikasi</dt><dd>{{ $order->paid_at?->setTimezone('Asia/Jakarta')->format('d/m/Y H:i') ?? 'Belum terverifikasi' }} @if($order->paid_at) WIB @endif</dd></div><div><dt class="text-sm text-slate-600">Aktivasi hak paket</dt><dd>{{ $order->activated_at?->setTimezone('Asia/Jakarta')->format('d/m/Y H:i') ?? 'Belum diaktifkan' }} @if($order->activated_at) WIB @endif</dd></div></dl>
@if($order->requires_follow_up)<p role="status" class="mt-4 rounded-lg bg-amber-50 p-3 text-amber-900">Transaksi memerlukan pemeriksaan admin. Refund otomatis tidak tersedia.</p>@endif
@if($order->status==='paid' && $order->event->publication_status!=='published')<p class="mt-4 text-slate-600">Pembayaran tercatat, event belum dipublikasikan. Buka event untuk memeriksa status organisasi, assessment, jadwal dan kelengkapan publikasi.</p>@endif
<div class="mt-6 flex flex-wrap gap-4">
@if(!$admin && $order->status==='pending' && $order->event->status==='approved' && $order->event->lifecycle_status==='upcoming' && $order->event->publication_status!=='suspended' && $order->event->ends_at > now())
@if($order->checkout_url)<a class="rounded-lg bg-indigo-600 px-4 py-2 text-white" href="{{ $order->checkout_url }}" rel="noreferrer">Buka pembayaran Sandbox</a>@else<form method="POST" action="{{ route('organizer.orders.checkout',$order) }}" x-data="{busy:false}" @submit="busy=true">@csrf<x-button x-bind:disabled="busy">Siapkan checkout Sandbox</x-button></form>@endif
@endif
<form method="POST" action="{{ route($admin ? 'admin.orders.sync' : 'organizer.orders.sync',$order) }}" x-data="{busy:false}" @submit="busy=true">@csrf<x-button variant="secondary" x-bind:disabled="busy">Sinkronkan status</x-button></form>
@if(!$admin)<a class="text-indigo-700 underline" href="{{ route('organizer.events.show',$order->event_id) }}">Kembali ke event</a>@endif</div>
</x-section-card>
